-- ============================================================================
-- km_daily_snapshots — Pre-computed JSON blob per (date, symbol)
-- ============================================================================
-- Purpose: Single row = everything the Dashboard needs for one day.
--   Eliminates 7+ separate table queries per user per page load.
--   2000 users = 1 DB read (edge function caches the rest).
--
-- Generated by: snapshot_generator.py (runs daily after pipeline)
-- Consumed by:  Supabase Edge Function /api/snapshot
-- ============================================================================

CREATE TABLE IF NOT EXISTS km_daily_snapshots (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  date          DATE NOT NULL,
  symbol        TEXT NOT NULL,
  version       INT NOT NULL DEFAULT 1,
  snapshot      JSONB NOT NULL,
  generated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_snapshot_date_symbol UNIQUE (date, symbol)
);

-- Primary access pattern: lookup by (date, symbol) — covered by UNIQUE constraint
-- Secondary: range queries for calendar view (all days in a month)
CREATE INDEX IF NOT EXISTS idx_snapshots_symbol_date
  ON km_daily_snapshots (symbol, date DESC);

-- ── Row Level Security ──
ALTER TABLE km_daily_snapshots ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read (same data for everyone)
CREATE POLICY "snapshots_public_read"
  ON km_daily_snapshots FOR SELECT
  USING (true);

-- Only service_role can write (Python pipeline uses service key)
-- No INSERT/UPDATE/DELETE policies for anon/authenticated = blocked by default
-- Service role key bypasses RLS entirely, so no explicit write policy needed.

COMMENT ON TABLE km_daily_snapshots IS
  'Pre-computed daily dashboard data. One JSONB blob per (date, symbol) containing '
  'risk scores, panchang, planetary positions, signals, sectors, outlook, and market data. '
  'Generated by snapshot_generator.py, served via Edge Function with in-memory caching.';

COMMENT ON COLUMN km_daily_snapshots.snapshot IS
  'Complete dashboard payload: {risk, panchang, planets, aspects, events, signals, sectors, outlook, market}';

COMMENT ON COLUMN km_daily_snapshots.version IS
  'Schema version for backward compatibility. Increment when snapshot structure changes.';
