-- Generated by generate_venus_visibility.py; requires migration 235.
-- No source overrides. Angular combustion and visibility remain distinct.
BEGIN;
SET LOCAL lock_timeout='10s';
SELECT pg_advisory_xact_lock(hashtext('venus_visibility_ujjain_v1'));
INSERT INTO public.km_astro_event_definition(event_type,display_name,shape,definition,definition_status) VALUES
 ('venus_tara_asta','Venus Tara Asta','point','Calculated disappearance boundary at Ujjain. Visibility model v1; not angular combustion or a station.','defined'),
 ('venus_tara_udaya','Venus Tara Udaya','point','Calculated reappearance boundary at Ujjain. Visibility model v1; not a station.','defined'),
 ('venus_tara_asta_period','Venus Tara Asta Period','period','Interval between calculated disappearance and reappearance at Ujjain. No manual overrides.','defined')
ON CONFLICT(event_type) DO NOTHING;
CREATE TABLE IF NOT EXISTS public.km_venus_visibility_windows (
 start_ts timestamptz PRIMARY KEY, end_ts timestamptz NOT NULL,
 start_event text NOT NULL CHECK(start_event IN ('morning_last','evening_last')),
 end_event text NOT NULL CHECK(end_event IN ('morning_first','evening_first')),
 parameters jsonb NOT NULL,
 CHECK(end_ts>start_ts),
 CHECK((start_event='morning_last' AND end_event='evening_first') OR
       (start_event='evening_last' AND end_event='morning_first'))
);
CREATE TEMP TABLE venus_visibility_import(start_ts timestamptz,end_ts timestamptz,start_event text,end_event text) ON COMMIT DROP;
INSERT INTO venus_visibility_import VALUES
('1990-01-15T18:00:54+05:30','1990-01-21T06:45:07+05:30','evening_last','morning_first'),
('1990-10-10T06:07:35+05:30','1990-11-29T17:49:31+05:30','morning_last','evening_first'),
('1991-08-13T18:58:41+05:30','1991-08-27T05:46:31+05:30','evening_last','morning_first'),
('1992-05-15T05:32:30+05:30','1992-07-06T19:25:56+05:30','morning_last','evening_first'),
('1993-03-28T18:39:35+05:30','1993-04-01T06:08:50+05:30','evening_last','morning_first'),
('1993-12-21T06:44:50+05:30','1994-02-11T18:27:20+05:30','morning_last','evening_first'),
('1994-10-25T17:54:19+05:30','1994-11-07T06:14:16+05:30','evening_last','morning_first'),
('1995-07-31T05:42:28+05:30','1995-09-15T18:38:27+05:30','morning_last','evening_first'),
('1996-06-06T19:15:01+05:30','1996-06-16T05:16:33+05:30','evening_last','morning_first'),
('1997-02-26T06:38:25+05:30','1997-04-25T19:01:01+05:30','morning_last','evening_first'),
('1998-01-13T18:02:52+05:30','1998-01-18T06:53:41+05:30','evening_last','morning_first'),
('1998-10-07T06:03:46+05:30','1998-11-27T17:48:02+05:30','morning_last','evening_first'),
('1999-08-11T19:01:16+05:30','1999-08-25T05:42:43+05:30','evening_last','morning_first'),
('2000-05-12T05:33:11+05:30','2000-07-04T19:24:59+05:30','morning_last','evening_first'),
('2001-03-26T18:40:38+05:30','2001-03-30T06:04:01+05:30','evening_last','morning_first'),
('2001-12-19T06:45:02+05:30','2002-02-08T18:27:00+05:30','morning_last','evening_first'),
('2002-10-22T17:54:31+05:30','2002-11-05T06:07:40+05:30','evening_last','morning_first'),
('2003-07-28T05:37:17+05:30','2003-09-12T18:44:36+05:30','morning_last','evening_first'),
('2004-06-04T19:17:51+05:30','2004-06-13T05:23:42+05:30','evening_last','morning_first'),
('2005-02-24T06:41:19+05:30','2005-04-23T18:58:41+05:30','morning_last','evening_first'),
('2006-01-10T17:57:48+05:30','2006-01-16T06:49:12+05:30','evening_last','morning_first'),
('2006-10-05T06:04:33+05:30','2006-11-24T17:50:18+05:30','morning_last','evening_first'),
('2007-08-09T19:04:00+05:30','2007-08-22T05:50:00+05:30','evening_last','morning_first'),
('2008-05-09T05:34:11+05:30','2008-07-02T19:24:10+05:30','morning_last','evening_first'),
('2009-03-24T18:42:59+05:30','2009-03-27T06:13:24+05:30','evening_last','morning_first'),
('2009-12-17T06:45:43+05:30','2010-02-06T18:24:22+05:30','morning_last','evening_first'),
('2010-10-20T18:01:59+05:30','2010-11-02T06:12:01+05:30','evening_last','morning_first'),
('2011-07-26T05:37:40+05:30','2011-09-10T18:44:09+05:30','morning_last','evening_first'),
('2012-06-01T19:09:04+05:30','2012-06-11T05:18:31+05:30','evening_last','morning_first'),
('2013-02-21T06:40:00+05:30','2013-04-20T19:00:21+05:30','morning_last','evening_first'),
('2014-01-08T18:00:14+05:30','2014-01-14T06:45:19+05:30','evening_last','morning_first'),
('2014-10-03T06:06:12+05:30','2014-11-22T17:48:46+05:30','morning_last','evening_first'),
('2015-08-07T19:07:06+05:30','2015-08-20T05:45:24+05:30','evening_last','morning_first'),
('2016-05-07T05:38:38+05:30','2016-06-29T19:26:48+05:30','morning_last','evening_first'),
('2017-03-21T18:37:25+05:30','2017-03-25T06:09:06+05:30','evening_last','morning_first'),
('2017-12-14T06:41:02+05:30','2018-02-03T18:24:04+05:30','morning_last','evening_first'),
('2018-10-17T18:00:12+05:30','2018-10-31T06:05:32+05:30','evening_last','morning_first'),
('2019-07-24T05:38:31+05:30','2019-09-08T18:45:04+05:30','morning_last','evening_first'),
('2020-05-30T19:09:54+05:30','2020-06-09T05:14:41+05:30','evening_last','morning_first'),
('2021-02-19T06:42:00+05:30','2021-04-18T18:57:21+05:30','morning_last','evening_first'),
('2022-01-05T17:55:06+05:30','2022-01-11T06:54:21+05:30','evening_last','morning_first'),
('2022-09-30T06:01:44+05:30','2022-11-19T17:51:58+05:30','morning_last','evening_first'),
('2023-08-05T19:11:33+05:30','2023-08-18T05:41:31+05:30','evening_last','morning_first'),
('2024-05-04T05:39:00+05:30','2024-06-27T19:25:19+05:30','morning_last','evening_first'),
('2025-03-19T18:38:44+05:30','2025-03-22T06:19:30+05:30','evening_last','morning_first'),
('2025-12-12T06:41:18+05:30','2026-02-01T18:21:19+05:30','morning_last','evening_first'),
('2026-10-14T18:00:27+05:30','2026-10-28T06:10:13+05:30','evening_last','morning_first'),
('2027-07-21T05:34:01+05:30','2027-09-05T18:50:17+05:30','morning_last','evening_first'),
('2028-05-28T19:11:19+05:30','2028-06-06T05:20:55+05:30','evening_last','morning_first'),
('2029-02-17T06:44:02+05:30','2029-04-16T18:55:17+05:30','morning_last','evening_first'),
('2030-01-03T17:58:19+05:30','2030-01-09T06:48:42+05:30','evening_last','morning_first'),
('2030-09-28T06:02:36+05:30','2030-11-17T17:50:04+05:30','morning_last','evening_first')
;
-- Fail closed if a rerun would silently introduce a competing method or dates.
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM public.km_venus_visibility_windows w JOIN venus_visibility_import i
 ON tstzrange(w.start_ts,w.end_ts,'[]') && tstzrange(i.start_ts,i.end_ts,'[]')
 WHERE (w.start_ts,w.end_ts,w.start_event,w.end_event) IS DISTINCT FROM
       (i.start_ts,i.end_ts,i.start_event,i.end_event)
 OR w.parameters IS DISTINCT FROM '{"location": "Ujjain", "geopos": [75.7885, 23.1793, 494.0], "atmosphere": [1013.25, 25.0, 40.0, 0.24], "observer": [36.0, 3.25, 0, 0, 0, 0], "ephemeris": "Moshier", "timezone": "Asia/Kolkata", "engine": "2.10.03", "method_version": "venus_visibility_ujjain_v1", "flags": 260, "precision": "calculated_visibility_model", "manual_overrides": false}'
 ::jsonb) THEN RAISE EXCEPTION 'Visibility method/date conflict: explicit migration required'; END IF;
END $$;
INSERT INTO public.km_venus_visibility_windows
 SELECT i.*,'{"location": "Ujjain", "geopos": [75.7885, 23.1793, 494.0], "atmosphere": [1013.25, 25.0, 40.0, 0.24], "observer": [36.0, 3.25, 0, 0, 0, 0], "ephemeris": "Moshier", "timezone": "Asia/Kolkata", "engine": "2.10.03", "method_version": "venus_visibility_ujjain_v1", "flags": 260, "precision": "calculated_visibility_model", "manual_overrides": false}'
 ::jsonb FROM venus_visibility_import i
ON CONFLICT(start_ts) DO NOTHING;
CREATE OR REPLACE VIEW public.km_venus_visibility_calendar AS
 SELECT e.event_type||':'||to_char(w.start_ts AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS')||'Z' AS event_key,e.event_type,d.display_name,d.shape,
 (e.start_ts AT TIME ZONE 'Asia/Kolkata')::date AS start_date,
 (e.end_ts AT TIME ZONE 'Asia/Kolkata')::date AS end_date,e.start_ts,e.end_ts,
 'calculated_visibility_model'::text AS precision,
 'swiss_ephemeris'::text AS source,w.parameters->>'method_version' AS calculation_method,
 w.start_event,w.end_event,w.parameters
 FROM public.km_venus_visibility_windows w CROSS JOIN LATERAL (VALUES
 ('venus_tara_asta',w.start_ts,w.start_ts),
 ('venus_tara_udaya',w.end_ts,w.end_ts),
 ('venus_tara_asta_period',w.start_ts,w.end_ts)
 ) e(event_type,start_ts,end_ts)
 JOIN public.km_astro_event_definition d USING(event_type);
-- Stable unified reader; migration 235's daily-source refresh remains unchanged.
CREATE OR REPLACE VIEW public.km_venus_calendar AS
 SELECT event_key,event_type,display_name,shape,start_date,end_date,start_ts,end_ts,precision,source,calculation_method
 FROM public.km_venus_event_calendar
 UNION ALL
 SELECT event_key,event_type,display_name,shape,start_date,end_date,start_ts,end_ts,precision,source,calculation_method
 FROM public.km_venus_visibility_calendar;
REVOKE ALL ON public.km_venus_visibility_windows FROM PUBLIC;
DO $$ DECLARE role_name text; BEGIN
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated','kd_readonly','kd_app','kd_admin'] LOOP
  IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=role_name) THEN
   EXECUTE format('REVOKE ALL ON public.km_venus_visibility_windows FROM %I',role_name);
   EXECUTE format('GRANT SELECT ON public.km_venus_visibility_windows,public.km_venus_visibility_calendar,public.km_venus_calendar TO %I',role_name);
  END IF;
 END LOOP;
END $$;
NOTIFY pgrst,'reload schema';
COMMIT;
