import { useEffect, useState } from 'react';
import { Card } from '@/components/ui';

interface VaNiResponse {
  date: string;
  interpretation: string;
  cached: boolean;
}

const TIMEOUT_MS = 90_000;

export default function VaNiCard({ date }: { date: string }) {
  const [data, setData]       = useState<VaNiResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(false);

  useEffect(() => {
    setLoading(true);
    setError(false);
    setData(null);

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

    fetch('/api/vani/daily', {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ date }),
      signal:  controller.signal,
    })
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((d: VaNiResponse) => {
        setData(d);
        setLoading(false);
      })
      .catch(() => {
        setError(true);
        setLoading(false);
      })
      .finally(() => clearTimeout(timer));

    return () => {
      controller.abort();
      clearTimeout(timer);
    };
  }, [date]);

  return (
    <Card rounded="xxl" className="px-5 py-4">
      {/* Header */}
      <div className="flex items-center gap-1.5 mb-3">
        <span
          className="text-accent-indigo select-none"
          style={loading ? { animation: 'vani-pulse 2s ease-in-out infinite' } : undefined}
        >
          ✦
        </span>
        <span className="text-[11px] font-black uppercase tracking-[0.18em] text-accent-indigo">
          VaNi
        </span>
        <span className="text-[10px] text-muted tracking-wide">· Atmospheric Reading</span>
      </div>

      {/* Body */}
      {loading && (
        <p className="text-[11px] text-muted leading-relaxed">
          VaNi is reading today's atmosphere...
        </p>
      )}
      {error && !loading && (
        <p className="text-[11px] text-muted leading-relaxed">
          VaNi is reflecting... check back shortly.
        </p>
      )}
      {data && !loading && (
        <p className="text-[12px] text-secondary leading-relaxed">{data.interpretation}</p>
      )}

      {/* Footer */}
      <p className="text-[9px] text-muted mt-3 pt-2 border-t border-kd-border">
        Generated by VaNi · Educational only · Not investment advice
      </p>

      {/* Pulse keyframe — scoped inline so it doesn't pollute global styles */}
      <style>{`
        @keyframes vani-pulse {
          0%, 100% { opacity: 0.4; }
          50%       { opacity: 1.0; }
        }
      `}</style>
    </Card>
  );
}
