import { useEffect, useState } from 'react';
import { Loader2 } from 'lucide-react';
import { Card } from '@/components/ui';

interface VaNiResponse {
  date: string;
  interpretation: string;
  cached: boolean;
}

export default function VaNiCard({ date }: { date: string }) {
  const [data, setData]       = useState<VaNiResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    fetch('/api/vani/daily', {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ date }),
    })
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((d: VaNiResponse) => { setData(d); setLoading(false); })
      .catch(() => { setError('VaNi is unavailable.'); setLoading(false); });
  }, [date]);

  return (
    <Card rounded="xxl" className="px-5 py-4">
      {/* Header */}
      <div className="flex items-center gap-1.5 mb-3">
        <span className="text-accent-indigo select-none">✦</span>
        <span className="text-[11px] font-black uppercase tracking-[0.18em] text-accent-indigo">
          VaNi
        </span>
        <span className="text-[10px] text-muted tracking-wide">· Atmospheric Reading</span>
      </div>

      {/* Body */}
      {loading && (
        <div className="flex items-center gap-2 text-muted">
          <Loader2 className="w-3.5 h-3.5 animate-spin" />
          <span className="text-[11px]">VaNi is reading today's atmosphere…</span>
        </div>
      )}
      {error && !loading && (
        <p className="text-[11px] text-risk-red">{error}</p>
      )}
      {data && !loading && (
        <p className="text-[12px] text-secondary leading-relaxed">{data.interpretation}</p>
      )}

      {/* Footer */}
      <p className="text-[9px] text-muted mt-3 pt-2 border-t border-kd-border">
        Generated by VaNi · Educational only · Not investment advice
      </p>
    </Card>
  );
}
