import { create } from 'zustand';
import type { StructureSection } from '@/config/marketStructureIntents';

export type StructurePeriod = 22 | 44 | 66;
interface StructureState {
  period: StructurePeriod;
  selectedDate: string | null;
  section: StructureSection;
  setPeriod: (period: StructurePeriod) => void;
  setDate: (selectedDate: string | null) => void;
  setSection: (section: StructureSection) => void;
}
export const useMarketStructureStore = create<StructureState>(set => ({
  period: 66, selectedDate: null, section: 'participation',
  setPeriod: period => set({ period }),
  setDate: selectedDate => set({ selectedDate }),
  setSection: section => set({ section }),
}));

// The target IDs are owned by MarketStructureView, never generated by the LLM.
export function showStructureEvidence(section: Exclude<StructureSection, 'historical'>) {
  useMarketStructureStore.getState().setSection(section);
  requestAnimationFrame(() => document.getElementById(`structure-${section}`)?.scrollIntoView({
    behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'center',
  }));
}
