/** Reviewed educational copy. Shipped with the app: no LLM request or time expiry.
 * Increment the version whenever these explanations or their underlying rules change.
 * Golden Line scanners are deliberately excluded from this first release. */
export const SCANNER_INTRODUCTION_VERSION = 4
export interface ScannerIntroductionCopy {name:string;story:string;read:string;caution:string;signals:{title:string;text:string}[]}
const score = {title:'5D and 22D scores',text:'Read the recent score alongside the broader baseline. A stronger recent reading can help you spot a difference between the two horizons; it does not prove improvement since yesterday. These are research scores, not measured investor inflows.'}
const rs = {title:'MagicRS',text:'MagicRS adds relative-strength context against NIFTY 500. A stock can rise yet lag the benchmark, or fall while holding up better than it. Read the displayed zone alongside the price move; relative strength is not a forecast.'}
const rsi = {title:'RSI',text:'RSI helps put the recent price move in context. Above 70 is a high reading, not automatic confirmation or an automatic reversal. Below 30 is a low reading, not proof of a bottom. RSI is supporting context here, not the rule that admits a stock to this scan.'}
const volume = {title:'Participation',text:'Compare trading activity with its usual level. Unusually active trading can give context to a price move, but does not identify who traded or establish that the move will continue.'}
function period(name:string,period:string,up:boolean):ScannerIntroductionCopy {
 return {name,story:`This scan finds stocks whose latest close is ${up?'above':'below'} the previous ${period}’s closing price. It helps you compare where stocks stand against that shared reference.`,read:`Start with the ${period==='week'?'WTD':'MTD'} change and the previous ${period}’s close, then check whether the recent score and relative-strength picture support or conflict with that move.`,caution:`This is a comparison with one closing reference. It does not mean the stock ${up?'rose':'fell'} every day, or that the next ${period} will follow the same direction.`,signals:[{title:period==='week'?'Weekly reference':'Monthly reference',text:`The percentage change is measured from the previous ${period}’s closing price. It is different from the latest one-day change and from the 5D/22D research scores.`},score,rs,rsi]}
}
export const SCANNER_INTRODUCTIONS:Record<string,ScannerIntroductionCopy> = {
 breakout_surge:{name:'Breakout Surge',story:'A stock has closed above its recent trading range on an up day. Breakout Surge brings these stocks together so you can inspect the move and the evidence around it.',read:'Start with the breakout level and how far price has moved beyond it. Then compare recent and broader scores, trading activity, and relative strength. Agreement adds context; mixed signals deserve a closer look.',caution:'A breakout is an observation, not a promise that the move will hold. A large move beyond the level or a high RSI reading is not, by itself, stronger confirmation.',signals:[score,volume,rs,rsi]},
 flower_pot_burst:{name:'Flower Pot Burst',story:'This scan follows quiet coils and two kinds of expansion: BURST to the upside and SHATTER to the downside. During a COIL, the trading range contracts and activity becomes quieter.',read:'Identify the phase first: COIL is a forming setup, BURST an upside event, and SHATTER a downside event. Compare activity and tracked outcomes within the relevant phase.',caution:'A quiet coil does not establish the direction or timing of a future move. Both BURST and SHATTER can fail to follow through; earlier outcomes do not guarantee the next result.',signals:[{title:'COIL, BURST and SHATTER',text:'COIL is compression, BURST an upside expansion, and SHATTER a downside expansion. Check the phase and session date; a coil does not imply either outcome.'},volume,rs,{title:'Tracked outcomes',text:'Use follow-through and outcome information to study what happened after a recorded setup. Keep that historical observation separate from an expectation about a current coil.'}]},
 weekly_movers:period('Weekly Movers','week',true),
 monthly_movers:period('Monthly Movers','month',true),
 weekly_decliners:period('Weekly Decliners','week',false),
 monthly_decliners:period('Monthly Decliners','month',false),
 breakdown_watch:{name:'Breakdown Surge',story:'A stock has closed below its recent trading floor on a down day. Breakdown Surge collects these observations so you can examine where price is losing support.',read:'Start with the breakdown level and the distance below it. Compare recent and broader scores, activity, and MagicRS to see whether weakness is accompanied by other caution signals.',caution:'A break below a floor does not establish continued declines. A low RSI reading is not proof of a bottom, and this scan is not an instruction to sell or short.',signals:[score,volume,rs,rsi]},
}
