/** Reviewed educational copy. Shipped with the app: no LLM request or time expiry.
 * Increment the version whenever these explanations or their underlying rules change.
 * Version 10 (migration 224) drops VaNi Weakness Watch, retired from the Stage
 * family. Its copy leaving is itself a content change: the shared stage lesson
 * names each scanner's role, so a lesson still describing a fifth entry would
 * be teaching a screener the user cannot open.
 * Version 9 (migration 218) adds the Golden Line pair, which had been the only
 * Studio family with no introduction at all, and restates the retest as a
 * seven-session window across both exchanges. */
export const SCANNER_INTRODUCTION_VERSION = 10
export interface ScannerIntroductionCopy {name:string;story:string;read:string;caution:string;signals:{title:string;text:string}[]}
const score = {title:'5D and 22D scores',text:'Read the recent score alongside the broader baseline. A stronger recent reading can help you spot a difference between the two horizons; it does not prove improvement since yesterday. These are research scores, not measured investor inflows.'}
const rs = {title:'MagicRS',text:'MagicRS adds relative-strength context against NIFTY 500. A stock can rise yet lag the benchmark, or fall while holding up better than it. Read the displayed zone alongside the price move; relative strength is not a forecast.'}
const rsi = {title:'RSI',text:'RSI helps put the recent price move in context. Above 70 is a high reading, not automatic confirmation or an automatic reversal. Below 30 is a low reading, not proof of a bottom. RSI is supporting context here, not the rule that admits a stock to this scan.'}
const volume = {title:'Participation',text:'Compare trading activity with its usual level. Unusually active trading can give context to a price move, but does not identify who traded or establish that the move will continue.'}
function period(name:string,period:string,up:boolean):ScannerIntroductionCopy {
 return {name,story:`This scan finds stocks whose latest close is ${up?'above':'below'} the previous ${period}’s closing price. It helps you compare where stocks stand against that shared reference.`,read:`Start with the ${period==='week'?'WTD':'MTD'} change and the previous ${period}’s close, then check whether the recent score and relative-strength picture support or conflict with that move.`,caution:`This is a comparison with one closing reference. It does not mean the stock ${up?'rose':'fell'} every day, or that the next ${period} will follow the same direction.`,signals:[{title:period==='week'?'Weekly reference':'Monthly reference',text:`The percentage change is measured from the previous ${period}’s closing price. It is different from the latest one-day change and from the 5D/22D research scores.`},score,rs,rsi]}
}
const gl_line = {title:'The Golden Line',text:'The Golden Line is the 150-bar mean of the closing price — a slow reference level, not a support line anyone is defending. Price crossing or touching it is an observation about where the close sits relative to that average.'}
const gl_volume = {title:'The volume signature',text:'These events are recorded on sessions that also printed a volume-drive or accumulation bar, so the crossing carries participation rather than being a quiet drift across the level. The signature describes the session, not who traded in it.'}
const gl_delivery = {title:'Delivery percentage — NSE only',text:'The delivery column is blank for every BSE-listed row, because that figure is not published for BSE in this dataset. Blank means not measured on this exchange. It does not mean delivery was low, and a BSE row is not weaker evidence than an NSE row for having an empty cell.'}
export const SCANNER_INTRODUCTIONS:Record<string,ScannerIntroductionCopy> = {
 breakout_surge:{name:'Breakout Surge',story:'A stock has closed above its recent trading range on an up day. Breakout Surge brings these stocks together so you can inspect the move and the evidence around it.',read:'Start with the breakout level and how far price has moved beyond it. Then compare recent and broader scores, trading activity, and relative strength. Agreement adds context; mixed signals deserve a closer look.',caution:'A breakout is an observation, not a promise that the move will hold. A large move beyond the level or a high RSI reading is not, by itself, stronger confirmation.',signals:[score,volume,rs,rsi]},
 flower_pot_burst:{name:'Flower Pot Burst',story:'This scan follows quiet coils and two kinds of expansion: BURST to the upside and SHATTER to the downside. During a COIL, the trading range contracts and activity becomes quieter.',read:'Identify the phase first: COIL is a forming setup, BURST an upside event, and SHATTER a downside event. Compare activity and tracked outcomes within the relevant phase.',caution:'A quiet coil does not establish the direction or timing of a future move. Both BURST and SHATTER can fail to follow through; earlier outcomes do not guarantee the next result.',signals:[{title:'COIL, BURST and SHATTER',text:'COIL is compression, BURST an upside expansion, and SHATTER a downside expansion. Check the phase and session date; a coil does not imply either outcome.'},volume,rs,{title:'Tracked outcomes',text:'Use follow-through and outcome information to study what happened after a recorded setup. Keep that historical observation separate from an expectation about a current coil.'}]},
 weekly_movers:period('Weekly Movers','week',true),
 monthly_movers:period('Monthly Movers','month',true),
 weekly_decliners:period('Weekly Decliners','week',false),
 monthly_decliners:period('Monthly Decliners','month',false),
 gl_breakout:{name:'Golden Line Breakout',story:'A stock has closed back above the 150-day Golden Line, having been at or below it on the previous session, and did so on a session with a volume signature. This scan collects those single-session reclaims across NSE and BSE.',read:'Start with the distance above the line, then read the volume signature and the recent and broader scores. A reclaim is one session’s close relative to a slow average; the wider picture is what gives it context.',caution:'Closing back above a long average is an observation about one session, not evidence that the level will hold or that a trend has turned. A larger distance above the line is not stronger confirmation.',signals:[gl_line,gl_volume,gl_delivery,score,rs]},
 gl_retest:{name:'Golden Line Retest',story:'A stock came back down to the Golden Line during a session, closed back above it, and had already been holding above the line for some time beforehand. This scan looks back over the last SEVEN trading sessions across NSE and BSE, so a test from earlier in the week is still on the list.',read:'Read “Retested” first — it says how many sessions ago the test happened, and a row from six sessions ago is a different observation from one printed today. “Move Since” shows how far price has travelled from that bar’s close; the optional “Still at the line” toggle keeps only the rows that have moved less than 5% either way. “Days Above GL” is measured on the retest bar itself, not today.',caution:'Holding a long average on one session says nothing about whether it will hold again. A stock that has barely moved since its retest is not thereby safer or closer to an entry — it has simply not travelled. Several of these stocks may retest and then lose the level.',signals:[gl_line,{title:'Retested — sessions ago',text:'The window is seven TRADING sessions, not seven calendar days, so a holiday does not shorten it. Today reads as “Today”; the oldest row a list can hold is six sessions back. A stock that tested the line more than once in the window is shown once, on its most recent test.'},{title:'Move Since, and the 5% toggle',text:'This is the percentage change from the retest bar’s close to the latest close, and it can be positive or negative. The toggle is a reading preference, not part of what admits a stock to the scan; a row with no reading is excluded by the toggle rather than quietly kept.'},gl_volume,gl_delivery,rs]},
 breakdown_watch:{name:'Breakdown Surge',story:'A stock has closed below its recent trading floor on a down day. Breakdown Surge collects these observations so you can examine where price is losing support.',read:'Start with the breakdown level and the distance below it. Compare recent and broader scores, activity, and MagicRS to see whether weakness is accompanied by other caution signals.',caution:'A break below a floor does not establish continued declines. A low RSI reading is not proof of a bottom, and this scan is not an instruction to sell or short.',signals:[score,volume,rs,rsi]},
}

/** One shared stage lesson, with an accurate role for each existing scanner. */
export const STAGE_SCANNER_IDS = ['stage_2_watch','stage_2_leaders','stage_3_watch','stage_4_leaders'] as const
const stageSignals = [
 {title:'Stage and confirmation',text:'The recorded stage describes the stock’s trend structure. Stage 2 Watch contains candidates; it is different from the recorded Stage 2 cohort. Check the stage and confirmation fields rather than treating every watchlist name as an established advance.'},
 {title:'Moving averages',text:'These smooth past closing prices so you can compare the shorter and longer trend. Their position and slope provide context, but they respond after price changes and can give mixed readings around transitions.'},
 {title:'Time in stage',text:'Use the recorded stage date and available duration to understand how long the condition has been observed. Limited history can hide the true start. A long duration does not tell you how much longer the stage will last.'},
 rs,
]
const stageRoles:Record<string,{name:string;story:string;read:string}> = {
 stage_2_watch:{name:'Stage 2 Watch',story:'This is the transition watchlist: recorded Stage 2 candidates with price and moving-average alignment checks. It helps you study an emerging advance before treating it as an established Stage 2 condition.',read:'Start with the candidate stage, then inspect the chart, moving averages and relative strength. A candidate can improve, remain unresolved or weaken; it is not a confirmed breakout.'},
 stage_2_leaders:{name:'Stage 2 Leaders',story:'This scanner collects stocks recorded in Stage 2: the advancing part of the framework. It lets you compare stocks already showing an upward trend structure.',read:'Start with the recorded stage and confirmation, then compare time in stage, distance from prior highs and MagicRS. A rising stock can still be extended or lag its benchmark.'},
 stage_3_watch:{name:'Stage 3 Watch',story:'This scanner focuses on recorded Stage 3 stocks whose shorter and longer moving averages are close together. It helps you inspect a trend that is losing clarity.',read:'Check the chart for a broadening range or weakening advance, then inspect moving averages and relative strength. Stage 3 can resolve in either direction; it does not establish a coming decline.'},
 stage_4_leaders:{name:'Stage 4 Leaders',story:'This is the declining-trend scanner. It selects recorded Stage 4 stocks with price below the 50-day average and the 50-day average below the 200-day average.',read:'Read “Leaders” here as the scanner’s name, not positive leadership. Compare the weakness and relative-strength readings; a rebound within a decline does not by itself establish recovery.'},
}
for(const id of STAGE_SCANNER_IDS) SCANNER_INTRODUCTIONS[id]={...stageRoles[id],caution:'Stages describe observed conditions, not a fixed timetable. Stocks can revisit stages or change direction; the illustrated sequence is not a forecast or a buy/sell instruction.',signals:stageSignals}

export const FLOW_SCANNER_IDS = ['conviction_flow','power_buy','volume_drive'] as const
const flowCaution='Flow describes recorded trading conditions. Delivery activity and inferred flow labels do not identify an investor, prove institutional buying or establish future price direction.'
Object.assign(SCANNER_INTRODUCTIONS, {
 conviction_flow:{name:'Conviction Flow',story:'Recent delivery value is elevated against its broader baseline while price remains near its short-term average. This scan helps you study increased participation before assuming that price has broken out.',read:'Compare the 5D and 22D average delivery amounts, then inspect price distance from the 20-day average and the chart. A high recent reading can accompany a sideways, rising or falling price.',caution:flowCaution,signals:[{title:'Average delivery amount · 5D / 22D',text:'These are money-value readings across two lookback windows, distinct from the Flow 5D and Flow 22D research scores. Compare like-for-like fields and check how much history is available.'},{title:'Delivery surge',text:'The displayed multiple expresses recent delivery activity relative to its broader baseline. It is a comparison across windows, not proof that activity increased since yesterday.'},{title:'Distance from the 20-day average',text:'This scanner keeps price relatively close to its short-term average. Near the average does not mean undervalued, low risk or ready to break out.'},rs]},
 power_buy:{name:'Strength Confluence',story:'This scan brings together stocks with qualifying strength conditions in industries that are leading or rotating in. It connects the individual stock with its wider industry setting.',read:'Start with the industry context, then inspect the stock’s price structure, recorded activity condition and MagicRS. Qualifying combinations can differ; appearing here does not mean every positive signal is present.',caution:flowCaution,signals:[{title:'Industry context',text:'Leading or rotating-in describes the recorded industry condition. It is wider context, not a claim that this stock leads its industry or that all constituents are strong.'},{title:'Confluence',text:'Several observations can support a research case, but related measures can overlap. Do not count them as independent confirmations or assume all qualifying stocks met the same combination.'},rs,volume]},
 volume_drive:{name:'Volume Drive',story:'This scan collects stocks with recorded volume-drive or accumulation-bar events. It helps you examine unusually active sessions and compare delivery participation around those events.',read:'Identify the event first, then compare delivery percentage, recent price movement and MagicRS. Volume-drive events are ordered first; delivery percentage and recent price momentum help order the results within the event groups.',caution:flowCaution,signals:[{title:'Recorded volume event',text:'An event label describes what was observed in a completed session. It is different from a prediction of a future burst. Check the candle: a positive daily change does not always mean the close was above the open.'},{title:'Delivery percentage',text:'This describes the share of traded quantity marked for delivery. It differs from delivery value and total volume. A high percentage alone does not identify who traded or why.'},volume,rs]},
})


export const DISCOVERY_SCANNER_IDS = ['wg_stirring','waking_giants','wg_ascent'] as const
const discoveryCaution='These are current recorded journey states, not a timetable. A quiet base may never wake, a wake may fail, and an ascent may pause or return to sleep. Delivery and relative strength do not identify investors or predict an outcome.'
Object.assign(SCANNER_INTRODUCTIONS, {
 wg_stirring:{name:'Stirring',story:'The stock is still in a long base, but quiet delivery-backed activity has become visible. No multi-year ceiling break has been recorded for this current journey.',read:'Start with the years in the base and the count of quiet building sessions. Then inspect the turn above the Golden Line, the distance from the old ceiling, and the daily, weekly and monthly clocks. A turn is not yet a wake.',caution:discoveryCaution,signals:[{title:'Quiet building sessions',text:'The recorded count looks for delivery participation during relatively quiet trading. It describes a repeated condition, not the identity or intent of the traders.'},{title:'Turn versus wake',text:'A turn is the current constructive run above the 150-session Golden Line with weekly context. A wake requires a later break of the multi-year closing ceiling. These dates and levels answer different questions.'},{title:'Old ceiling',text:'The earlier high close is the level to inspect. Being near it can be interesting, but proximity does not mean it will break.'},{title:'Three clocks',text:'Daily, weekly and monthly readings show whether strength spans more than one horizon. Missing readings should not be treated as negative or as agreement.'}]},
 waking_giants:{name:'Waking Giants',story:'The stock has recorded a wake after closing beyond a multi-year ceiling, at or above the Golden Line. This tab focuses on recent wakes while the transition is still forming.',read:'Compare the wake date and closing level with today’s price. Then read distance from the wake, base length and the three clocks. The tab starts with a 90-day wake window that can be widened to 120 or 150 days; this changes the displayed cohort, not the wake date.',caution:discoveryCaution,signals:[{title:'Wake and former ceiling',text:'The wake marks the first recorded close beyond the prior multi-year closing ceiling in the current journey. A wake event is an observation; price can move back below that level.'},{title:'Golden Line',text:'The 150-session average supplies longer-term price context. A wake is checked against that line; holding above it later is a separate observation.'},{title:'Distance from wake',text:'Compare today’s close with the stored wake close and date. A positive or negative distance shows what happened since the event, not what will happen next.'},{title:'Three clocks',text:'Daily, weekly and monthly readings help show whether the move has broadened across horizons. Full alignment is a separate confirmation step, not implied merely by appearing in Waking Giants.'}]},
 wg_ascent:{name:'Ascent',story:'The journey has moved beyond the initial wake and recorded confirmation across its daily, weekly and monthly clocks. This tab follows the continuing journey, including periods of rest.',read:'Compare the current close with the wake and turn closes, then inspect journey age, the three current clocks and the resting marker. Confirmation belongs to the journey history; today’s readings can differ from the confirmation day.',caution:discoveryCaution,signals:[{title:'Confirmed journey',text:'Ascent is recorded after the wake when the three clocks align and the broader closing structure confirms. It is a journey state, not a guarantee that all clocks remain positive today.'},{title:'Wake versus turn',text:'The turn marks an earlier constructive run; the wake marks the later multi-year ceiling break. Compare both recorded levels and dates before judging progress.'},{title:'Resting',text:'A confirmed journey can pause. The resting marker distinguishes a pause from a fresh wake; check current price and clocks rather than assuming uninterrupted gains.'},{title:'Current alignment',text:'Read the daily, weekly and monthly symbols separately. Missing or changed readings matter; the aggregate alignment score alone does not say which clock changed.'}]},
})


export const MARKET_SCANNER_IDS = ['smart_money','quiet_accumulation','distribution_warning','power_sell'] as const
const marketCaution='These scanner names describe measured price, delivery and relative-strength conditions. They do not identify institutions or investor orders, establish a capital inflow or outflow, or predict the next move.'
Object.assign(SCANNER_INTRODUCTIONS, {
 smart_money:{name:'Smart Money Loading',story:'This scan looks for high delivery participation and positive stock strength within industries that currently rank strongly. “Smart Money” is the scanner’s label for this pattern; the data does not reveal who traded.',read:'Begin with the industry setting, then compare the stock’s delivery percentage and relative-strength reading. High delivery can occur alongside a mixed price move; inspect the chart and session date before drawing a conclusion.',caution:marketCaution,signals:[{title:'Leading industry context',text:'The industry qualifies through its recorded ranking or participation condition. That does not make every stock in it an industry leader.'},{title:'Delivery percentage',text:'This is the share of traded quantity marked for delivery. It is different from delivery value and cannot identify an institution or the direction of its position.'},{title:'Stock strength',text:'The recorded stock strength reading gives another lens on price participation. A positive reading is an observation, not proof of continued demand.'},{title:'Check the price move',text:'Compare the delivery signal with the stock’s own close and chart. Participation alone does not tell you whether the stock is beginning or finishing a move.'}]},
 quiet_accumulation:{name:'Quiet Rising Flow',story:'This scan looks for recorded accumulation conditions in industries whose participation is improving but which have not yet been classified as leaders. It is an early observation, not a recorded breakout.',read:'Check the industry’s change in participation, the stock’s accumulation reading and the recent activity markers. Then compare price and delivery on the chart. “Quiet” refers to the observed pattern; it does not mean hidden orders were identified.',caution:marketCaution,signals:[{title:'Improving, not yet leading',text:'An improving industry is different from a currently leading one. This scanner focuses on that earlier industry context; an improvement can stall.'},{title:'Accumulation reading',text:'The recorded accumulation label summarizes trading conditions. It is an inferred signal, not an account-level record of who accumulated shares.'},{title:'Recent participation',text:'Compare current and recent activity readings before calling the pattern persistent. A single observation does not establish a trend.'},{title:'Price still matters',text:'Read the chart alongside the quiet signal. A stock can have improving participation without clearing its prior ceiling.'}]},
 distribution_warning:{name:'Falling Flow Warnings',story:'This scan looks for stocks that previously had a strong relative-strength zone but now read lower, alongside a recorded distribution-style activity signal or downward volume divergence.',read:'Compare the earlier and current strength zones, then inspect the activity marker and price chart. The warning is about deterioration from the earlier condition; it is not evidence that an institution exited.',caution:marketCaution,signals:[{title:'Earlier strength versus now',text:'The earlier Strong Bull reading is a reference point. Current readings below it show a change in relative strength, which need not be a price decline on every session.'},{title:'Distribution-style activity',text:'An activity marker can support a caution reading, but it does not reveal whether particular investors sold.'},{title:'Downward volume divergence',text:'Volume and price can send mixed signals. A divergence marker calls for inspection of the sessions behind it; it is not a guaranteed reversal.'},{title:'Watch the current chart',text:'Compare the signal date, present price structure and current zone. A warning can fade or intensify as new sessions arrive.'}]},
 power_sell:{name:'Weakness Confluence',story:'This scanner joins a lagging or rotating-out industry with qualifying stock weakness conditions. Different rows can qualify through different condition combinations.',read:'Start with the industry context, then inspect the stock’s price position, relative-strength zone and recorded distribution or flow condition. Industry weakness and stock weakness are related observations, not a sell instruction.',caution:marketCaution,signals:[{title:'Lagging industry context',text:'A lagging or rotating-out industry is the wider setting. It does not mean every constituent is weak or that the industry cannot recover.'},{title:'Stock condition',text:'Qualifying rows can use a recorded distribution condition or a combination of weaker price, relative strength, flow label and activity. Do not assume every signal is present in every row.'},{title:'Relative strength',text:'Compare the stock with its benchmark and its own price trend. Relative weakness is different from an absolute loss on the day.'},{title:'Participation',text:'Unusual activity can add context to a weak price structure. It does not identify sellers or establish that weakness will continue.'}]},
})
