-- Generated by generate_venus_visibility.py; requires migration 235.
-- No source overrides. Angular combustion and visibility remain distinct.
BEGIN;
SET LOCAL lock_timeout='10s';
SELECT pg_advisory_xact_lock(hashtext('venus_visibility_ujjain_v1'));
INSERT INTO public.km_astro_event_definition(event_type,display_name,shape,definition,definition_status) VALUES
 ('venus_tara_asta','Venus Tara Asta','point','Calculated disappearance boundary at Ujjain. Visibility model v1; not angular combustion or a station.','defined'),
 ('venus_tara_udaya','Venus Tara Udaya','point','Calculated reappearance boundary at Ujjain. Visibility model v1; not a station.','defined'),
 ('venus_tara_asta_period','Venus Tara Asta Period','period','Interval between calculated disappearance and reappearance at Ujjain. No manual overrides.','defined')
ON CONFLICT(event_type) DO NOTHING;
CREATE TABLE IF NOT EXISTS public.km_venus_visibility_windows (
 start_ts timestamptz PRIMARY KEY, end_ts timestamptz NOT NULL,
 start_event text NOT NULL CHECK(start_event IN ('morning_last','evening_last')),
 end_event text NOT NULL CHECK(end_event IN ('morning_first','evening_first')),
 parameters jsonb NOT NULL,
 CHECK(end_ts>start_ts),
 CHECK((start_event='morning_last' AND end_event='evening_first') OR
       (start_event='evening_last' AND end_event='morning_first'))
);
CREATE TEMP TABLE venus_visibility_import(start_ts timestamptz,end_ts timestamptz,start_event text,end_event text) ON COMMIT DROP;
INSERT INTO venus_visibility_import VALUES
-- GENERATED_VALUES
;
-- Fail closed if a rerun would silently introduce a competing method or dates.
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM public.km_venus_visibility_windows w JOIN venus_visibility_import i
 ON tstzrange(w.start_ts,w.end_ts,'[]') && tstzrange(i.start_ts,i.end_ts,'[]')
 WHERE (w.start_ts,w.end_ts,w.start_event,w.end_event) IS DISTINCT FROM
       (i.start_ts,i.end_ts,i.start_event,i.end_event)
 OR w.parameters IS DISTINCT FROM -- GENERATED_PARAMETERS
 ::jsonb) THEN RAISE EXCEPTION 'Visibility method/date conflict: explicit migration required'; END IF;
END $$;
INSERT INTO public.km_venus_visibility_windows
 SELECT i.*,-- GENERATED_PARAMETERS
 ::jsonb FROM venus_visibility_import i
ON CONFLICT(start_ts) DO NOTHING;
CREATE OR REPLACE VIEW public.km_venus_visibility_calendar AS
 SELECT e.event_type||':'||to_char(w.start_ts AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS')||'Z' AS event_key,e.event_type,d.display_name,d.shape,
 (e.start_ts AT TIME ZONE 'Asia/Kolkata')::date AS start_date,
 (e.end_ts AT TIME ZONE 'Asia/Kolkata')::date AS end_date,e.start_ts,e.end_ts,
 'calculated_visibility_model'::text AS precision,
 'swiss_ephemeris'::text AS source,w.parameters->>'method_version' AS calculation_method,
 w.start_event,w.end_event,w.parameters
 FROM public.km_venus_visibility_windows w CROSS JOIN LATERAL (VALUES
 ('venus_tara_asta',w.start_ts,w.start_ts),
 ('venus_tara_udaya',w.end_ts,w.end_ts),
 ('venus_tara_asta_period',w.start_ts,w.end_ts)
 ) e(event_type,start_ts,end_ts)
 JOIN public.km_astro_event_definition d USING(event_type);
-- Stable unified reader; migration 235's daily-source refresh remains unchanged.
CREATE OR REPLACE VIEW public.km_venus_calendar AS
 SELECT event_key,event_type,display_name,shape,start_date,end_date,start_ts,end_ts,precision,source,calculation_method
 FROM public.km_venus_event_calendar
 UNION ALL
 SELECT event_key,event_type,display_name,shape,start_date,end_date,start_ts,end_ts,precision,source,calculation_method
 FROM public.km_venus_visibility_calendar;
REVOKE ALL ON public.km_venus_visibility_windows FROM PUBLIC;
DO $$ DECLARE role_name text; BEGIN
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated','kd_readonly','kd_app','kd_admin'] LOOP
  IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=role_name) THEN
   EXECUTE format('REVOKE ALL ON public.km_venus_visibility_windows FROM %I',role_name);
   EXECUTE format('GRANT SELECT ON public.km_venus_visibility_windows,public.km_venus_visibility_calendar,public.km_venus_calendar TO %I',role_name);
  END IF;
 END LOOP;
END $$;
NOTIFY pgrst,'reload schema';
COMMIT;
